#!/bin/bash

#
# setup important services
#

# needed for protonvpn to get the secrets out of gnome-keyring
# see: https://github.com/ProtonVPN/linux-cli/issues/49
nm-applet &

#
# setup WM config
#

# setup monitor layout
if [[ $(xrandr -q | grep 'HDMI-0 connected') ]]; then
    xrandr \
        --output HDMI-0 --mode 1280x1024 --pos 0x285  --rotate normal \
        --output DP-2   --mode 2560x1440 --pos 1280x0 --rotate normal
else
    xrandr --output DP-2 --mode 2560x1440 --rotate normal
fi

# setup compositor
picom -b

# background
nitrogen --restore &
