theme = "gruvbox_original_dark_hard"

[editor]
bufferline = "always"
rulers = [100]
line-number = "relative"
cursorline = true
color-modes = true
auto-save = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "selections", "file-encoding", "file-type", "file-line-ending", "position"]

[editor.indent-guides]
render = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
tab = "→"
newline = "¬"

[editor.lsp]
auto-signature-help = false

[keys.normal]
# mnemonic to other char -> S-char keybinds
X = ["extend_line_above"]

# move lines up and down, currently only works on selecions that don't cross lines
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "move_line_up"]
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after", "move_line_down"]

# custom space sub menu
[keys.normal.space.space]
# most common reflow length
r = ":reflow 100"

# list just recipes
j = ":sh just --list --unsorted"

# just sub menu
[keys.normal.space.space.J]
l = ":sh just --list --unsorted"
b = ":sh just build"
c = ":sh just check"
t = ":sh just test"
