theme = "gruvbox_original_dark_hard"

[editor]
rulers = [100]
line-number = "relative"
cursorline = true
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "selections", "file-encoding", "file-type", "file-line-ending", "position"]

[editor.indent-guides]
render = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
tab = "→"
newline = "¬"

[editor.lsp]
auto-signature-help = false