[[language]]
name = "python"
rulers = [80]


[[language]]
name = "latex"
indent = { tab-width = 4, unit = "    " }


[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "^typ(st)?$"
file-types = ["typ"]
roots = []
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
language-server.command = "typst-lsp"
# dynamic capability registration is not yet supported, log:
# Ignoring a client/registerCapability request because dynamic capability registration is not enabled. Please report this upstream to the language server
# config = { settings = { exportPdf = 'onType' } }

[[grammar]]
name = "typst"
source = { git = "https://github.com/frozolotl/tree-sitter-typst/", rev = "af40989c1a2e724a9625cae412c17a60969280ca" }


[[language]]
name = "just"
scope = "source.just"
injection-regex = "^just?$"
file-types = ["just", "justfile"]
roots = []
comment-token = "#"

[[grammar]]
name = "just"
source = { git = "https://github.com/IndianBoy42/tree-sitter-just", rev = "4e5f5f3ff37b12a1bbf664eb3966b3019e924594" }
